[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.36", features = ["full"] }
axum = { version = "0.7.4", features = ["ws"] }
tower-http = { version = "0.5.2", features = ["cors", "fs", "trace"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.7", features = ["v4"] }
rand = "0.8.5"
futures-util = "0.3.30"
chrono = { version = "0.4.34", features = ["serde"] }
sha2 = "0.10.8"
hex = "0.4.3"
urlencoding = "2.1.3"
